name: BausWords
favicon: null
layout_spectrum: 0.8221501582302153
typography_spectrum: 0.17401998327113688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9364553391933441
  lightness: 0.747172852512449
  saturation: 0.14986090874299407
  rhythmicContrast: 0.5373940323479474
purpose: []
