name: BausWords
favicon: null
layout_spectrum: 0.8221501582302153
typography_spectrum: 0.17401998327113688
title: 'BausCode::Words'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#79e8df'
    - '#41ddd2'
    - '#d8f6f4'
    - '#e6a336'
    - '#07d0c0'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
