name: BausWords
favicon: null
layout_spectrum: 0.8221501582302153
typography_spectrum: 0.17401998327113688
title: 'BausCode::Words'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212122'
    - '#ffffff'
    - '#6fc8da'
    - '#d3d2d2'
    - '#5693a0'
  brandStrength: 0.8125
  lightness: 0.747172852512449
  saturation: 0.14986090874299407
  rhythmicContrast: 0.5373940323479474
purpose: []
